

#logging:
 # level:
  # org.springframework: DEBUG

spring:
 jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
 datasource:
  url : jdbc:h2:mem:testdb
  

